Repository lambda-art-portfolio-bweu/art-portfolio-frontend, pull requests merged in 2019-07, with the labels that each got.

#18 Add API constant and fix artist profile description
  src/actions/artists.js
  src/actions/const.js
  src/actions/posts.js
  src/components/GlobalMenu.jsx
  src/components/profile/Profile.jsx
  src/container/Homepage.jsx
  src/reducers/post.js
Labels: bug, enhancement

#20 General fix
  package-lock.json
  src/actions/artists.js
  src/actions/const.js
  src/components/postslist/PostsList.jsx
  src/components/profile/Profile.jsx
  src/container/ProfileView.jsx
  src/reducers/artist.js
  src/reducers/post.js
Labels: bug

#21 Enable edit profile functionality
  .vscode/launch.json
  src/App.js
  src/actions/artists.js
  src/actions/const.js
  src/components/Artists.jsx
  src/components/profile/Profile.jsx
  src/container/Homepage.jsx
  src/container/ProfileView.jsx
Labels: bug, enhancement

#22 Refactor file names to be more consistent everywhere
  .vscode/settings.json
  src/App.js
  src/components/HeaderMenu.jsx
  src/components/Post.jsx
  src/components/Profile.jsx
  src/components/artistsblock/Artist.jsx
  src/components/artistsblock/ArtistsGrid.jsx
  src/components/postsblock/PostCard.jsx
  src/components/postsblock/PostsGrid.jsx
  src/components/postslist/PostCard.jsx
  src/container/HomeView.jsx
  src/container/PostView.jsx
  src/container/ProfileView.jsx
Labels: enhancement

#23 Post edit and delete capabilities
  .vscode/launch.json
  src/App.js
  src/actions/artists.js
  src/actions/posts.js
  src/components/AddPostModal.jsx
  src/components/Post.jsx
  src/components/Profile.jsx
  src/components/artistsblock/Artist.jsx
  src/components/artistsblock/ArtistsGrid.jsx
  src/components/postsblock/PostCard.jsx
  src/components/postsblock/PostsGrid.jsx
  src/container/HomeView.jsx
  src/container/PostView.jsx
Labels: enhancement

#27 Edit image for profile picture and post cover image
  src/actions/artists.js
  src/assets/camera.svg
  src/components/Post.jsx
  src/components/Profile.jsx
  src/container/ProfileView.jsx
Labels: enhancement

#29 Implemented routing with username
  src/App.js
  src/actions/artists.js
  src/components/HeaderMenu.jsx
  src/components/Login.jsx
  src/components/Profile.jsx
  src/components/Signup.jsx
  src/components/artistsblock/Artist.jsx
  src/components/postsblock/PostCard.jsx
  src/components/postsblock/PostsGrid.jsx
Labels: enhancement

#31 Various improvements and fixes
  src/actions/artists.js
  src/components/HeaderMenu.jsx
  src/components/Login.jsx
  src/components/Profile.jsx
  src/components/postsblock/PostCard.jsx
  src/container/ProfileView.jsx
  src/reducers/artist.js
Labels: bug, enhancement
